"""Randomised variants of an incident scenario: every actor, gate change and object is shifted in time
independently, and each staged incident moves with the entity it is about. So the answer key is still written
by the scenario, never by the rules.

    uv run python -m scenarios.variants scenarios/library/SCN-M0-001.yaml --seeds 1-5 --out data/scenarios/variants

Shifts keep every time >= 0 and inside the scenario's duration.
"""

import argparse
import copy
import random
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[1]


def variant(base: dict, seed: int, max_shift_s: float = 15.0) -> dict:
    rng = random.Random(seed)
    doc = copy.deepcopy(base)
    dur = float(doc["duration_s"])
    shifts: dict[str, float] = {}

    def pick(times: list[float], key: str) -> float:
        lo, hi = -min(times), dur - max(times)  # stay inside [0, duration]
        s = rng.uniform(max(-max_shift_s, lo), min(max_shift_s, hi)) if hi > lo else 0.0
        shifts[key] = round(s, 1)
        return shifts[key]

    for a in doc.get("actors", []):
        s = pick([k["t"] for k in a["keyframes"]], a["id"])
        for k in a["keyframes"]:
            k["t"] = round(k["t"] + s, 2)
    by_asset: dict[str, list] = {}
    for c in doc.get("asset_changes", []):
        by_asset.setdefault(c["id"], []).append(c)
    for aid, changes in by_asset.items():  # one shift per gate keeps open/close pairs in order
        s = pick([c["t"] for c in changes], aid)
        for c in changes:
            c["t"] = round(c["t"] + s, 2)
    for o in doc.get("objects", []):
        s = pick([o["spawn_t"]] + ([o["remove_t"]] if o.get("remove_t") else []), o["id"])
        o["spawn_t"] = round(o["spawn_t"] + s, 2)
        if o.get("remove_t"):
            o["remove_t"] = round(o["remove_t"] + s, 2)
    for inc in doc.get("staged_incidents", []):
        inc["t"] = round(inc["t"] + shifts.get(inc["subject"], 0.0), 2)
    doc["id"] = f"SCN-V{base['id'].split('-')[-1]}-{seed:03d}"  # e.g. SCN-V001-007
    doc["name"] = f"{base['name']}_variant_{seed}"
    return doc


def main() -> int:
    from benchmarks.avoidance.crowd import parse_seeds

    ap = argparse.ArgumentParser()
    ap.add_argument("base")
    ap.add_argument("--seeds", default="1-5")
    ap.add_argument("--out", default=str(REPO / "data/scenarios/variants"))
    a = ap.parse_args()
    base = yaml.safe_load(Path(a.base).read_text())
    out = Path(a.out)
    out.mkdir(parents=True, exist_ok=True)
    for s in parse_seeds(a.seeds):
        doc = variant(base, s)
        path = out / f"{doc['id']}.yaml"
        path.write_text(f"# variant of {base['id']} (seed {s}), generated by scenarios/variants.py\n"
                        + yaml.safe_dump(doc, sort_keys=False))
        print(path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
